accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [

    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls')),
    path('accounts/', include('accounts.urls'))
]

def protected_file(request, path, document_root=None):
    return redirect('/property')

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from . import views

app_name ='property'

urlpatterns = [
    path('', views.index, name='index'),
    path('naver_excel', views.naver_excel, name='naver_excel'),
    path('naver_news_insert', views.naver_news_insert, name='naver_news_insert'),
    path('naver_list', views.naver_list, name='naver_list'),
    path('naver_view/<int:pk>/', views.naver_view, name='naver_view'),
    path('comment_create/<int:pk>/', views.comment_create, name='comment_create'),
    path('comment_modify/', views.comment_modify, name='comment_modify'),
    path('com_delete/<int:no>/<int:qno>/', views.com_delete, name='com_delete'),

]

templates/base/base2.html
{% load static %}

<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

    <!--부트스트랩 최신버전 CDN-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- CSS -->
    <!--    <link rel="stylesheet" href="../../static/css/uikit.min.css" />-->
    <!--    <script src="../../static/js/uikit.min.js"></script>-->
    <!--    <script src="../../static/js/uikit-icons.min.js"></script>-->
    <title>prototype</title>
</head>


<body>
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'property:index' %}">Main</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" name="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    {% if nickname != None %}
                    <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if nickname %}
                    {% else %}
                    <a class="nav-link" href="{% url 'accounts:register' %}">회원가입</a>
                    {% endif %}
                </li>

<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'property:naver_excel' %}">액셀 저장</a>-->
<!--                </li>-->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'property:naver_news_insert' %}">크롤링 가져오기</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'property:naver_list' %}">리스트</a>
                </li>



            </ul>
        </div>
    </div>
</nav>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>