config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls')),
    path('accounts/', include('accounts.urls'))
]

def protected_file(request, path, document_root=None):
    return redirect('/property')

urlpatterns += static(settings.MEDIA_URL, protected_file, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from . import views

app_name ='property'

urlpatterns = [
    path('', views.index, name='index'),
    path('naver_excel', views.naver_excel, name='naver_excel'),
    path('naver_news_insert', views.naver_news_insert, name='naver_news_insert'),
    path('naver_list', views.naver_list, name='naver_list'),
    path('naver_view/<int:pk>/', views.naver_view, name='naver_view'),
    path('comment_create/<int:pk>/', views.comment_create, name='comment_create'),
    path('comment_modify/', views.comment_modify, name='comment_modify'),
    path('com_delete/<int:no>/<int:qno>/', views.com_delete, name='com_delete'),

]

property/models.py
from django.db import models

# Create your models here.



class newsList(models.Model):
    id = models.AutoField(primary_key=True)
    news_title = models.CharField(max_length=200, null=True, verbose_name='TITLE')
    news_url = models.CharField(max_length=100, null=True, verbose_name='URL')
    rg_date = models.DateTimeField(auto_now_add=True, verbose_name='등록일')
    lede = models.CharField(max_length=100, verbose_name='짧은 내용',  null=True, blank=True)
    writing = models.CharField(max_length=50, verbose_name='언론사', null=True, blank=True)
    comm = models.PositiveIntegerField(null=True, verbose_name='댓글 수')

    class Meta:
        managed = True
        db_table = 'news_lists'
        verbose_name = 'news'
        verbose_name_plural = 'news'


class news_comment(models.Model):
    no = models.AutoField(primary_key=True)
    rg_date = models.DateTimeField(auto_now_add=True, verbose_name='등록일자')
    register = models.CharField(max_length=30, verbose_name='작성자', null=True, blank=True)
    content = models.TextField(verbose_name='내용', null=True, blank=True)
    news_id = models.ForeignKey(newsList, on_delete=models.CASCADE, null=True, db_column="news_id")

    class Meta:
        managed = True
        db_table = 'news_comment'
        verbose_name = '댓글'
        verbose_name_plural = '댓글'

property/views.py
from django.shortcuts import render, redirect, get_object_or_404
import requests
import urllib.request as req

from pandas import DataFrame
from bs4 import BeautifulSoup, Comment
from datetime import datetime
import os
from .models import newsList, news_comment
from django.core.paginator import Paginator
import datetime
from datetime import date
from datetime import datetime
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
import json
from django.urls import reverse
from .decorators import login_required
import re


def index(request):
    nickname = request.session.get('nickname')

    url = "https://finance.naver.com/marketindex/"

    res = req.urlopen(url)
    soup = BeautifulSoup(res, "html.parser", from_encoding='euc-kr')

    name_nation = soup.select('h3.h_lst > span.blind')
    name_price = soup.select('span.value')

    nlist = {}
    i = 0
    for c_list in soup:
        try:

            nlist[i] = {'ntitle': name_nation[i].text, 'nnum': name_price[i].text}

            i = i + 1
        except IndexError:
            pass

    flist = nlist.values()
    context = {'nickname': nickname, 'flist': flist}
    return render(request, 'property/index.html', context)


# 엑셀 저장
def naver_excel(request):
    # naver finance 인기 검색 종목
    print('크롤링 시작')

    date = str(datetime.now())
    date_str = date.split()[0].replace('-', '')
    date = date[:date.rfind(':')].replace(' ', '_')
    date = date.replace(':', '시') + '분'

    urls = 'https://news.naver.com/main/list.naver?mode=LS2D&mid=shm&sid1=101&sid2=260'
    header = {'User-Agent': 'Mozilla/5.0'}
    res = requests.get(urls, headers=header)
    soup = BeautifulSoup(res.text, 'html.parser')

    # main_content > div.list_body.newsflash_body > ul.type06_headline > li:nth-child(1) > dl > dt:nth-child(2) > a

    news_dict = {}
    idx = 0
    cur_page = 1
    print('크롤링 중...')

    pages = soup.find('div', {'class': 'paging'})

    while True:
        main = soup.find('div', {'class': 'list_body newsflash_body'})

        li_list = main.find_all('dl')

        area_list = [li.find('dt') for li in li_list]
        # 사진없는 기사 포함된 경우 오류발생
        # area_list = [li.find('dt', {'class' : 'photo'}) for li in li_list]
        a_list = [area.find('a') for area in area_list]

        for n in a_list[:len(a_list)]:
            try:
                news_dict[idx] = {'title': n.find('img').get('alt').strip(), 'url': n.get('href')}
            except:
                news_dict[idx] = {'title': n.text.strip(), 'url': n.get('href')}
            idx += 1

        if cur_page < len(pages.find_all('a')) + 1:
            try:
                next_page_url = [p for p in pages.find_all('a') if p.text == str(cur_page + 1)][0].get('href')
                print("찐 왓다감")
            except:
                next_page_url = [p for p in pages.find_all('a') if p.text == '다음'][0].get('href')
                cur_page = 11
        elif cur_page > len(pages.find_all('a')) + 1:
            try:
                next_page_url = [p for p in pages.find_all('a') if p.text == str(cur_page + 1)][0].get('href')
                print("찐 왓다감")
            except:
                break
        elif cur_page == 40:
            break
        req = requests.get('https://news.naver.com/main/list.naver' + next_page_url, headers=header)
        soup = BeautifulSoup(req.text, 'html.parser')
        pages = soup.find('div', {'class': 'paging'})

        cur_page += 1

    print('크롤링 완료')

    news_df = DataFrame(news_dict).T

    folder_path = os.getcwd()

    xlsx_file_name = '네이버뉴스_{}.xlsx'.format(date)
    news_df.to_excel(xlsx_file_name, index=None, encoding='euc-kr')

    # context = {'news_dict': news_dict}

    return render(request, 'property/newsView.html')

    # print(news_df['title'])
    # print(news_df.iloc[:10])


# 크롤링 불러오기
@login_required
def naver_news_insert(request):
    print('크롤링 시작')

    urls = 'https://news.naver.com/main/list.naver?mode=LS2D&mid=shm&sid1=101&sid2=260'
    header = {'User-Agent': 'Mozilla/5.0'}
    res = requests.get(urls, headers=header)
    soup = BeautifulSoup(res.text, 'html.parser')


    print('크롤링 중...')

    pages = soup.find('div', {'class': 'paging'})
    #cur_page = 1
    cur_page = len(pages.find_all('a'))

    # cur_page = len(pages.find_all('a')) + 1
    # news = newsList.objects.all()

    # newslists = newsList.objects.all()
    while True:

        # cur_page <= (len(pages.find_all('a')) + 1):
        main = soup.find('div', {'class': 'list_body newsflash_body'})

        li_list = main.find_all('dl')

        area_list = [li.find('dt') for li in li_list]
        dd_list = [li.find('dd') for li in li_list]
        # 사진없는 기사 포함된 경우 오류발생
        # area_list = [li.find('dt', {'class' : 'photo'}) for li in li_list]
        a_list = [area.find('a') for area in area_list]
        span_list = [area.find('span') for area in dd_list]


        print(len(pages.find_all('a')))
        print('cur : ', cur_page)
        if cur_page == len(pages.find_all('a')):
            try:
                next_page_url = [p for p in pages.find_all('a') if p.text == str(cur_page + 1)][0].get('href')
                print('cur 작다 try : ', next_page_url)
            except:
                print('cur 동일 브레이크')
                break
        elif 0 <= cur_page < len(pages.find_all('a')):
            try:
                next_page_url = [p for p in pages.find_all('a') if p.text == str(cur_page + 1)][0].get('href')
                print('cur 크다 try : ', next_page_url)
            except:
                next_page_url = [p for p in pages.find_all('a') if p.text == '이전'][0].get('href')
                print('cur 작다 except : ', next_page_url)
        elif cur_page == -1:
            print('cur = 0 끝')
            break

        req = requests.get('https://news.naver.com/main/list.naver' + next_page_url, headers=header)
        soup = BeautifulSoup(req.text, 'html.parser')
        pages = soup.find('div', {'class': 'paging'})

        cur_page -= 1

        main = soup.find('div', {'class': 'list_body newsflash_body'})

        li_list2 = main.find_all('dl')

        for n in li_list2:
            news_title = n.find('a').text.strip()

            if news_title != "":
                news_title = n.find('a').text.strip()
                news_url = n.find('a').get('href')
                lede = n.find('span').text.strip()
                writing = n.find('span', {'class': 'writing'})
                if writing == None:
                    print('title 있음 pass')
                    pass
                else:
                    writing = writing.text.strip()
            else:
                news_title = n.find('img').get('alt').strip()
                news_url = n.find('a').get('href')
                lede = n.find('span').text.strip()
                writing = n.find('span', {'class': 'writing'})
                if writing == None:
                    print('title 사진 pass')
                    pass
                else:
                    writing = writing.text.strip()
            news = newsList.objects.filter(news_url=news_url).order_by('-rg_date')
            if news.count() == 0:
                # print('중복확인 저장 시작')
                newsList(
                    news_title=news_title,
                    news_url=news_url,
                    lede=lede,
                    writing=writing
                ).save()
    return redirect('property:naver_list')


# 네이버 리스트
@login_required
def naver_list(request):
    # 리스트 불러오기
    nickname = request.session.get('nickname')
    # nlist = newsList.objects.filter(rg_date__gte=date.today()).order_by('rg_date')
    # 검색 추가
    sort = request.GET.get('sort', '')
    query = request.GET.get('q', '')
    print(query)
    if sort == 'news_title':
        nlist = newsList.objects.filter(Q(news_title__icontains=query), rg_date__gte=date.today()).order_by('rg_date')
    elif sort == 'writing':
        nlist = newsList.objects.filter(Q(writing__icontains=query), rg_date__gte=date.today()).order_by('rg_date')
    else:
        print('리스트')
        nlist = newsList.objects.filter(rg_date__gte=date.today()).order_by('-rg_date')

    page = request.GET.get('page', '1')
    paginator = Paginator(nlist, 20)
    page_obj = paginator.get_page(page)
    context = {'page_obj': page_obj, 'nickname': nickname, 'sort': sort, 'query': query}
    print('리스트 완료')
    return render(request, 'property/news_list.html', context)


# 네이버 뉴스 뷰
def naver_view(request, pk):
    nickname = request.session.get('nickname')
    # 저장된 내용 불러오기
    detail_news = get_object_or_404(newsList, id=pk)
    comments = news_comment.objects.filter(news_id=pk).order_by('rg_date')
    print('url 불러오기 : ', detail_news.news_url)

    # 들어가면서 본문 내용 가져오기
    urls = detail_news.news_url
    header = {'User-Agent': 'Mozilla/5.0'}
    res = requests.get(urls, headers=header)
    soup = BeautifulSoup(res.text, 'html.parser')

    main = soup.find('div', {'class': 'go_trans _article_content'})


    for x in main.find_all("br"):
        print('1번쨰 : ', x)
        x.replace_with("\n")
        print('1번쨰 끝 : ', x)

    #
    # main_con = "".join([str(x) for x in main.contents])  # 최상위 태그 제거(=innerHtml 추출)
    # text = main_con.strip()

    text = main.text.strip()

    print(text)
    context = {'detail_news': detail_news, 'text': text, 'nickname': nickname, 'comments': comments}
    return render(request, 'property/news_view.html', context)


# 댓글/대댓글
def comment_create(request, pk):
    comment_count = news_comment.objects.filter(news_id=pk).count() + 1
    newscomm = get_object_or_404(newsList, id=pk)
    print("댓글 시작")
    if request.method == 'POST':
        print("댓글 저장")
        comment = news_comment()
        comment.register = request.POST.get('register')
        comment.content = request.POST.get('content')
        comment.news_id_id = pk
        comment.save()

        print('댓글수 저장')
        newscomm.comm = comment_count

templates/property/home.html
{% extends "base/base2.html" %}
{% block content %}
{% load humanize %}
{% load filter %}
<div>
    <ul>
        <li>
            <a class="nav-link" href="{% url 'property:index' %}">받아오기</a>
        </li>
    </ul>

</div>


{% endblock %}

templates/property/index.html
{% extends "base/base2.html" %}
{% block content %}
{% load humanize %}
<style>
    tr, td, th{
        border : 1px solid #dcdcdc;
        width : 350px;
        margin: 0 auto;
    }
    table {
    text-align: center;
    margin-left:auto;
    margin-right:auto;
    }

</style>


<div>

    <table>
        <tr>
            <th style="width:6%; font-size: 25px;">항목</th>
            <th style="width:10%; font-size: 25px;">환율</th>
        </tr>
        {% for i in flist %}
        <tr>
            <td>{{ i.ntitle }}</td>
            <td>{{ i.nnum |intcomma}}</td>
        </tr>
        {% endfor %}


    </table>


</div>


{% endblock %}

templates/property/news_list.html
{% extends "base/base2.html" %}
{% block content %}
{% load filter %}

<style>
    table {
    text-align: center;
    margin-left:auto;
    margin-right:auto;
    }
    tr, td, th{
        border : 1px solid #dcdcdc;
        width : 350px;
        margin: 0 auto;
    }
    tr.m:hover{
     background-color: #98bee0;
     cursor:pointer;
    }
    #paging{
        width:150px;
        margin:0 auto;
    }

</style>


<!--검색창 부분-->
<div>
    <form action="{% url 'property:naver_list' %}" method="GET">
        {% csrf_token %}
        <select name="sort" id="sort">
            <option value="news_title" id="news_title">Title</option>
            <option value="writing" id="writing">언론사</option>
        </select>
        <input type="search" placeholder="Tilte / 언론사 검색 가능" class="form-control mr-sm-2" name="q" value="{{ query }}">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search">검색</i></button>
    </form>
</div>



<!--리스트 부분-->
<div>
    <table>
        <tr>
            <th style="width:3%;">순번</th>
            <th style="width:15%;">제목</th>
            <th style="width:5%;">언론사</th>
            <th style="width:20%;">간략 내용</th>
            <th style="width:5%;">등록 일자</th>
        </tr>

        {% if page_obj %}
        {% for news in page_obj %}
        <tr class="m" onclick="location.href='{% url 'property:naver_view' news.id %}'">
            <td>{{ page_obj.paginator.count|sub:page_obj.start_index|sub:forloop.counter0|add:1   }}</td>
            {% if news.comm != None %}
            <td>{{ news.news_title }} <span style="color: red;">[{{ news.comm }}]</span></td>
            {% else %}
            <td>{{ news.news_title }}</td>
            {% endif %}
            <td>{{ news.writing }}</td>
            <td>{{ news.lede | truncatewords:10 }}</td>
            <td>{{ news.rg_date | date:'Y-m-d H:i:s' }}</td>
        </tr>

        {% endfor %}
        {% else %}
        <p>에러</p>
        {% endif %}

    </table>
</div>

<!--페이징 부분-->
<div class = "container" id="paging">
    {#first previous#}
    {% if page_obj.has_previous %}
    <a href="?q={{ query }}&page_obj={{ page_obj }}&page=1&sort={{sort}}">First</a>
    <a href="?q={{ query }}&page_obj={{ page_obj }}&page={{page_obj.previous_page_number}}&sort={{sort}}">Previous</a>
    {% endif %}
    {# 3of4 #}
    <span>{{page_obj.number}}</span>
    <span>of</span>
    <span>{{page_obj.paginator.num_pages}}</span>
    {# Next Last #}
    {% if page_obj.has_next %}
    <a href="?q={{ query }}&page_obj={{ page_obj }}&page={{page_obj.next_page_number}}&sort={{sort}}">Next</a>
    <a href="?q={{ query }}&page_obj={{ page_obj }}&page={{page_obj.paginator.num_pages}}&sort={{sort}}">Last</a>
    {%endif%}
</div>


{% endblock %}

templates/property/news_view.html
{% extends "base/base2.html" %}
{% block content %}

<style>
    textarea {
    border: none;
    resize: none;
    width: 100%;
    height: 15em;
    }

    #news_url:hover{
    background-color: #98bee0;
    cursor:pointer;
    }

    @media only screen and (max-width:600px){
	div#nav, div#article {
		width: 100%;
		height: auto;
	}

</style>


<script type="text/javascript">
<!--댓글 수정버튼 클릭시-->
const comment_update = (no) => {
    let comm_modify = document.querySelector(`#comm_modify${no}`);
    let comm_save = document.querySelector(`#comm_save${no}`);
    let comm_cancel = document.querySelector(`#comm_cancel${no}`);
    let comm_content = document.querySelector(`#comm_content${no}`);

    comm_modify.style.display = 'none';
    comm_save.style.display = 'inline-block';
    comm_cancel.style.display = 'inline-block';
    comm_content.readOnly = false;
    comm_content.focus();
}

<!--댓글 수정 취소버튼 클릭시-->
const comment_cancel = (no) => {
    let comm_modify = document.querySelector(`#comm_modify${no}`);
    let comm_save = document.querySelector(`#comm_save${no}`);
    let comm_cancel = document.querySelector(`#comm_cancel${no}`);
    let comm_content = document.querySelector(`#comm_content${no}`);

    comm_modify.style.display = 'inline-block';
    comm_save.style.display = 'none';
    comm_cancel.style.display = 'none';
    comm_content.readOnly = true;
}

<!--댓글 수정 저장-->
const comm_save = (no) => {
    let comm_content = document.querySelector(`#comm_content${no}`).value;
    let param ={
    'no' : no,
    'content' : comm_content
    }
    $.ajax({
        url : '{% url 'property:comment_modify' %}',
        type : 'POST',
        headers: {
            'X-CSRFTOKEN' : '{{ csrf_token }}'
        },
        data : JSON.stringify(param),
        success : function(data){
            console.log(data);
            if(data.result == 'ok') {
	            let comm_modify = document.querySelector(`#comm_modify${no}`);
                let comm_save = document.querySelector(`#comm_save${no}`);
                let comm_cancel = document.querySelector(`#comm_cancel${no}`);
                let comm_content = document.querySelector(`#comm_content${no}`);

                comm_modify.style.display = 'inline-block';
                comm_save.style.display = 'none';
                comm_cancel.style.display = 'none';
                comm_content.readOnly = true;
   }
        },
        error : function() {
            alert("에러");
        }
    })
    }

	function sub(){
	    code = $("#comm_chk").val();
        if(code.length == 0 ) {
            console.log("빈칸이야")
            return false;
        }
            console.log("들어가있어")
            return true
        }
</script>



<!--본문 부분-->
<div class="container my-3" id="nav">
    <div class="mb-3">
        <label for="news_titl">제목</label>
        <input type="text" class="form-control" name="news_titl" id="news_titl" value="{{ detail_news.news_title }}" readonly>
    </div>
    <div class="mb-3">
        <label for="rg_date">등록 일자</label>
        <input type="text" class="form-control" name="rg_date" id="rg_date" value="{{ detail_news.rg_date }}" readonly>
    </div>
    <div class="mb-3">
        <label for="writing">언론사</label>
        <input type="text" class="form-control" name="writing" id="writing" value="{{ detail_news.writing }}" readonly>
    </div>
    <div class="mb-3">
        <label for="news_url">URL</label>
        <input type="text" class="form-control" name="news_url" id="news_url" value="{{ detail_news.news_url }}"
               readonly onclick="window.open('{{ detail_news.news_url }}' )">
    </div>
    <div class="mb-3" id="article">
        <label for="content">본문 내용</label>
        <textarea class="form-control" name="content" id="content" readonly>{{ text }}</textarea>
    </div>
</div>





<!--댓글 표출 / 수정 / 삭제 부분-->
{% for comment in comments %}
<br><br>
<div class="container my-3">
    내용 :
    <input type="text" value="{{ comment.content }}" style="border:0 solid black; font-size:25px;" id="comm_content{{comment.no}}" readonly >
    <div>
        [ {{ comment.rg_date | date:'Y-m-d H:i:s' }} ] -  <b>{{ comment.register }}</b>
        <input type="button" class="btn btn-primary" value="수정" name="comm_modify" id="comm_modify{{comment.no}}" onclick="comment_update({{comment.no}})" >
        <input type="button" class="btn btn-primary" value="저장" name="comm_sava" id="comm_save{{comment.no}}" style="display:none" onclick="comm_save({{ comment.no }})">
        <input type="button" class="btn btn-primary" value="취소" name="comm_cancel" id="comm_cancel{{comment.no}}" style="display:none" onclick="comment_cancel({{ comment.no }})">
        <input type="button" class="btn btn-primary"  onclick="location.href='{% url 'property:com_delete' detail_news.id comment.no %}'" value="삭제">
    </div>
    <hr style="border: solid 1px black;">

</div>
{% endfor %}


<br><br>
<!--댓글 입력 부분-->
<div style="background-color: #E9ECEF" class="container my-3">
    <label for="comment_ins">댓글 입력</label>
    <form method="POST" id="comment_ins" name="comment_ins" action="{% url 'property:comment_create' detail_news.id %}" onsubmit="return sub();">
        {% csrf_token %}
        <div class="mb-3">
            <label for="register">등록자 : </label>
            {{ nickname }}
            <input name="register" type="hidden" value="{{ nickname }}" id="register"  readonly>
        </div>
        <div class="mb-3">
            <label for="content">내용 입력</label>
            <!--<textarea class="form-control" name="content" id="comm_chk" style="resize:none;"  ></textarea>-->
            <input type="text" class="form-control" name="content" id="comm_chk" >
        </div>
        <input type="submit" class="btn btn-primary" id="submit" value="댓글 등록">
    </form>
</div>





{% endblock %}